basePath: /
definitions:
  entity.Article:
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /article/{id}:
    get:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 获取文章详情
  /article/list:
    get:
      parameters:
      - description: 分类ID
        in: query
        name: cid
        type: integer
      - description: 菜单ID
        in: query
        name: mid
        type: integer
      - description: 标签ID
        in: query
        name: tid
        type: integer
      - description: 分页大小
        in: query
        name: pageSize
        type: integer
      - description: 页码
        in: query
        name: pageNum
        type: integer
      responses: {}
      summary: 获取文章列表
  /article/test:
    get:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/entity.Article'
      responses: {}
      summary: 测试
swagger: "2.0"
