// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAnother_for_unit_test = "another_for_unit_test"

// Another_for_unit_test mapped from table <another_for_unit_test>
type Another_for_unit_test struct {
	ID uint64 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
}

// TableName Another_for_unit_test's table name
func (*Another_for_unit_test) TableName() string {
	return TableNameAnother_for_unit_test
}
