// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameArticle_path = "article_path"

// Article_path mapped from table <article_path>
type Article_path struct {
	ID        int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	LocalPath string `gorm:"column:local_path;type:varchar(60);not null" json:"local_path"`
}

// TableName Article_path's table name
func (*Article_path) TableName() string {
	return TableNameArticle_path
}
