// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID       uint64 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;type:varchar(255);not null;uniqueIndex:name,priority:1;comment:分类名" json:"name"`
	Mid      uint64 `gorm:"column:mid;type:bigint unsigned;index:fk_menuchild_cids,priority:1;comment:菜单子项ID" json:"mid"`
	Homeshow *bool  `gorm:"column:homeshow;type:tinyint(1);not null;default:1;comment:主页是否显示" json:"homeshow"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
