// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID        uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	Name      string     `gorm:"column:name;type:longtext;not null" json:"name"`
	Qq        *string    `gorm:"column:qq;type:longtext" json:"qq"`
	Email     *string    `gorm:"column:email;type:longtext" json:"email"`
	Content   string     `gorm:"column:content;type:longtext;not null" json:"content"`
	Like      int64      `gorm:"column:like;type:bigint;not null" json:"like"`
	Check     bool       `gorm:"column:check;type:tinyint(1);not null" json:"check"`
	Show      bool       `gorm:"column:show;type:tinyint(1);not null" json:"show"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
