// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTags = "tags"

// Tags mapped from table <tags>
type Tags struct {
	ID    uint64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name  string  `gorm:"column:name;type:varchar(20);not null;uniqueIndex:name,priority:1" json:"name"` // 标签名
	Logo  *string `gorm:"column:logo;type:varchar(20)" json:"logo"`                                      // LOGO
	Color *string `gorm:"column:color;type:varchar(20)" json:"color"`                                    // 颜色
}

// TableName Tags's table name
func (*Tags) TableName() string {
	return TableNameTags
}
