// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_user_deleted_at,priority:1" json:"deleted_at"`
	Username  string         `gorm:"column:username;type:longtext;not null" json:"username"`
	Password  string         `gorm:"column:password;type:longtext;not null" json:"password"`
	Relation  string         `gorm:"column:relation;type:longtext;not null" json:"relation"`
	Role      *int64         `gorm:"column:role;type:bigint" json:"role"`
	Avatar    *string        `gorm:"column:avatar;type:longtext" json:"avatar"`
	NickName  *string        `gorm:"column:nick_name;type:longtext" json:"nick_name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
