// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_user_deleted_at,priority:1" json:"deleted_at"`
	Username  string         `gorm:"column:username;type:varchar(20);not null;comment:用户名" json:"username"`
	Password  []byte         `gorm:"column:password;type:varchar(20);not null;comment:密码" json:"password"`
	Relation  string         `gorm:"column:relation;type:varchar(20);not null;comment:关系" json:"relation"`
	Role      int64          `gorm:"column:role;type:bigint;comment:权限" json:"role"`
	Avatar    string         `gorm:"column:avatar;type:varchar(20);comment:头像" json:"avatar"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
